environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"
name: suryaicons

description: Flutter package for Surya Icons
repository: https://github.com/suryasarisa99/suryaicons-flutter
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
